name: End-to-end tests
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cypress run
        uses: cypress-io/github-action@v6
        # after the test run completes store videos and any screenshots
      - uses: actions/upload-artifact@v4
        if: always()
        with:
            name: cypress-screenshots
            path: cypress/screenshots
            if-no-files-found: ignore # 'warn' or 'error' are also available, defaults to `warn`
      - uses: actions/upload-artifact@v4
        with:
            name: cypress-videos
            path: cypress/videos
            if-no-files-found: ignore # 'warn' or 'error' are also available, defaults to `warn`
